# Generated by Django 5.2.4 on 2025-07-14 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upkeep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='initial_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
