# Generated by Django 5.2.4 on 2025-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upkeep', '0002_alter_item_initial_value_alter_item_purchase_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sub_location',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='initial_value',
            new_name='purchase_value',
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer_manual_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Retired'), (3, 'Broken')], default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
