# Generated by Django 5.2.4 on 2025-07-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upkeep', '0003_rename_sub_location_item_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_of_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
