# Generated by Django 5.2.4 on 2025-07-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upkeep', '0005_item_user_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
