# Generated by Django 5.2.9 on 2026-01-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_account_profile_account'),
        ('upkeep', '0007_task_snooze_count_task_snoozed_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.account'),
        ),
        migrations.AddField(
            model_name='location',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='common.account'),
        ),
    ]
