# Generated by Django 5.2.9 on 2026-01-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upkeep', '0008_item_account_location_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='account',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='upkeep.location'),
        ),
    ]
