# Generated by Django 6.1 on 2026-08-11 06:33

import django.core.validators
import upkeep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upkeep', '0009_remove_item_account_remove_item_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(upkeep.models.max_purchase_year)]),
        ),
    ]
